import '@vuesax-alpha/components/base/style'
import '@vuesax-alpha/theme-chalk/src/chip.scss'
import '@vuesax-alpha/theme-chalk/src/popper.scss'
import '@vuesax-alpha/theme-chalk/src/scrollbar.scss'
import '@vuesax-alpha/theme-chalk/src/select.scss'
import '@vuesax-alpha/theme-chalk/src/option.scss'
import '@vuesax-alpha/theme-chalk/src/option-group.scss'
