export const PROPS = {
  modelValue: null,
  labelPlaceholder: null,
  label: null,
  block: Boolean,
  iconAfter: Boolean,
  showPassword: Boolean,
  loading: Boolean,
  color: String,
  state: String,
  progress: Number,
  border: Boolean,
  shadow: Boolean,
  transparent: Boolean,
  textWhite: Boolean,
  square: Boolean,
  clearable: Boolean,
  disabled: Boolean,
  type: String,
};
