export const PKG_PREFIX = '@vuesax-alpha'
export const PKG_NAME = 'vuesax-alpha'
export const PKG_CAMELCASE_NAME = 'VuesaxAlpha'
export const PKG_CAMELCASE_LOCAL_NAME = 'VuesaxAlphaLocale'
export const PKG_BRAND_NAME = 'Vuesax Alpha'
